# Site settings
title: nocohub
locale: "ja-JP"
paginate: 5
motto:
email: noconoco.lib@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    機械学習,データ解析,ディープラーニング,C/C++,Pyhton,Java,プログラミング
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nocotan.github.io/" # the base hostname & protocol for your site
twitter_username: machinery81
github_username:  nocotan

# Build settings
markdown: kramdown

gems:
    - jekyll-paginate
